#development version of configurations
server:
  port: 8083

calendar:
  service:
    url: http://localhost:8082

#database connections
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/backend_cdac
    username: root
    password: 029906#Es

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: false
  security:
    #oauth configuration
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:test-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:test-client-secret}
            #/login/oauth2/code/google
            scope:
              - email
              - profile
              - openid
          github:
            client-id: ${GITHUB_CLIENT_ID:test-client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:test-client-secret}
            #/login/oauth2/code/github
            scope:
              - user:email
              - read:user


  #to find out the error in the log for understand that error and to resolve this
logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

security:
  jwt:
    secret: ${JWT_SECRET:saiofalvkasfbehwqpofhjashofjaswfpojasfvbafophfifonfoshjfwefjjfslajfsahfoshffasnbashf}
    issuer: ${JWT_ISSUER:api.auth.com}
    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:3600}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}
    refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}
    cookie-secure: ${JWT_COOKIE_SECURE:true}
    cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:true}
    cookie-same-site: ${JWT_COOKIE_SAME_SITE:lax}
    cookie-domain: ${JWT_COOKIE_DOMAIN:localhost}

app:
  auth:
    frontend:
      success-redirect: http://localhost:5173/auth/success
      failure-redirect: http://localhost:5173/auth/failure
#hikari:
#  pool-name: HikariCP
#  maximum-pool-size: 5
#  connection-timeout: 10000
#  idle-timeout: 600000
#  max-lifetime: 1800000
#  validation-timeout: 1800000
#  leak-detection-threshold: 0
#  initialization-fail-timeout: -1

cloudinary:
  cloud-name: dje5ue79u
  api-key: 173828562644592
  api-secret: VVcJaH3C4iu7YHEN5zcD5GyKLh8


